# Generated by Django 4.2 on 2024-02-14 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_measurement', models.DecimalField(decimal_places=6, max_digits=19)),
                ('measurement_type', models.CharField(choices=[('LE', 'Length'), ('WI', 'Width')], max_length=2)),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.itemcategory')),
            ],
        ),
    ]
