# Generated by Django 4.0.2 on 2022-02-21 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(blank=True, max_length=17, null=True, verbose_name='ISBN')),
                ('title', models.CharField(max_length=255)),
                ('goodreads_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('library_availability', models.CharField(blank=True, max_length=50, null=True)),
                ('read_status', models.CharField(choices=[('RE', 'Read'), ('TO', 'To Read'), ('CU', 'Currently Reading')], default='TO', max_length=2)),
                ('author', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.author')),
                ('genre', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.genre')),
                ('list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.list')),
            ],
        ),
    ]
