# Generated by Django 4.2 on 2024-01-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_item_itemcategory_measurementtype_remove_book_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemName',
            field=models.CharField(max_length=255),
        ),
    ]
