from django.core.management import BaseCommand

from app.models import Item, ItemCategory, MeasurementType


class Command(BaseCommand):
    help = 'Add animals to the Item class'

    def handle(self, *args, **options):
        item_weights = [
            {'itemName': 'Salt grain', 'itemMeasurement': 0.05, 'itemCategory': 'Food'},
            {'itemName': 'Feather', 'itemMeasurement': 0.1, 'itemCategory': 'Nature'},
            {'itemName': 'Ant', 'itemMeasurement': 1, 'itemCategory': 'Insect'},
            {'itemName': 'Paperclip', 'itemMeasurement': 1, 'itemCategory': 'Stationery'},
            {'itemName': 'Pencil', 'itemMeasurement': 10, 'itemCategory': 'Stationery'},
            {'itemName': 'Apple', 'itemMeasurement': 150, 'itemCategory': 'Fruit'},
            {'itemName': 'Smartphone', 'itemMeasurement': 200, 'itemCategory': 'Electronics'},
            {'itemName': 'Soda can', 'itemMeasurement': 355, 'itemCategory': 'Food'},
            {'itemName': 'Laptop', 'itemMeasurement': 2000, 'itemCategory': 'Electronics'},
            {'itemName': 'Small Dog', 'itemMeasurement': 5000, 'itemCategory': 'Household Items'},
            {'itemName': 'Watermelon', 'itemMeasurement': 5000000, 'itemCategory': 'Fruit'},
            {'itemName': 'Car Tire', 'itemMeasurement': 10000, 'itemCategory': 'Automobile'},
            {'itemName': 'Elephant', 'itemMeasurement': 5000000000, 'itemCategory': 'Wildlife'},
            {'itemName': 'Small Aircraft', 'itemMeasurement': 2000000, 'itemCategory': 'Transportation'},
            {'itemName': 'Adult Human', 'itemMeasurement': 70000, 'itemCategory': 'Human'},
            {'itemName': 'Blue Whale', 'itemMeasurement': 190000000, 'itemCategory': 'Marine Life'},
            {'itemName': 'Small Car', 'itemMeasurement': 1500, 'itemCategory': 'Automobile'},
            {'itemName': 'Motorcycle', 'itemMeasurement': 200, 'itemCategory': 'Transportation'},
            {'itemName': 'Baseball', 'itemMeasurement': 145, 'itemCategory': 'Sports Equipment'},
            {'itemName': 'Basketball', 'itemMeasurement': 600, 'itemCategory': 'Sports Equipment'},
            {'itemName': 'Adult Lion', 'itemMeasurement': 420000, 'itemCategory': 'Wildlife'},
            {'itemName': 'Small Elephant', 'itemMeasurement': 2500000, 'itemCategory': 'Wildlife'},
            {'itemName': 'Laptop Bag', 'itemMeasurement': 1000, 'itemCategory': 'Electronics'},
            {'itemName': 'Large Truck', 'itemMeasurement': 10000, 'itemCategory': 'Automobile'},
            {'itemName': 'Adult Giraffe', 'itemMeasurement': 1200000, 'itemCategory': 'Wildlife'},
            {'itemName': 'Bag of Flour', 'itemMeasurement': 1000, 'itemCategory': 'Food'},
            {'itemName': 'Human Brain', 'itemMeasurement': 1400, 'itemCategory': 'Human'},
            {'itemName': 'Backpack', 'itemMeasurement': 1000, 'itemCategory': 'Household Items'},
            {'itemName': 'Desktop Computer', 'itemMeasurement': 10000, 'itemCategory': 'Electronics'},
            {'itemName': 'Small TV', 'itemMeasurement': 5000, 'itemCategory': 'Electronics'},
            {'itemName': 'Soccer Ball', 'itemMeasurement': 410, 'itemCategory': 'Sports Equipment'},
            {'itemName': 'Adult Tiger', 'itemMeasurement': 300000, 'itemCategory': 'Wildlife'},
            {'itemName': 'Adult Rhino', 'itemMeasurement': 2300000, 'itemCategory': 'Wildlife'},
            {'itemName': 'Small Boat', 'itemMeasurement': 1500, 'itemCategory': 'Transportation'},
            {'itemName': 'Empty Coffee Cup', 'itemMeasurement': 200, 'itemCategory': 'Household Items'},
            {'itemName': 'Canoe', 'itemMeasurement': 30000, 'itemCategory': 'Transportation'},
            {'itemName': 'Car Battery', 'itemMeasurement': 15000, 'itemCategory': 'Automobile'},
            {'itemName': 'Adult Hippo', 'itemMeasurement': 1500000, 'itemCategory': 'Wildlife'},
            {'itemName': 'Small Avocado', 'itemMeasurement': 150, 'itemCategory': 'Food'},
            {'itemName': 'Motorcycle Helmet', 'itemMeasurement': 1000, 'itemCategory': 'Accessories'},
            {'itemName': 'Pair of Jeans', 'itemMeasurement': 700, 'itemCategory': 'Clothing'},
            {'itemName': 'Large Pumpkin', 'itemMeasurement': 5000, 'itemCategory': 'Food'},
            {'itemName': 'Desktop Monitor', 'itemMeasurement': 5000, 'itemCategory': 'Electronics'},
            {'itemName': 'Small Cat', 'itemMeasurement': 4000, 'itemCategory': 'Household Items'},
            {'itemName': 'Adult Kangaroo', 'itemMeasurement': 55000, 'itemCategory': 'Wildlife'},
            {'itemName': 'Small Fish (e.g., Goldfish)', 'itemMeasurement': 15, 'itemCategory': 'Pets'},
            {'itemName': 'Smartphone Charger', 'itemMeasurement': 100, 'itemCategory': 'Electronics'},
            {'itemName': 'Small Backpack', 'itemMeasurement': 500, 'itemCategory': 'Household Items'},
            {'itemName': 'Compact Disc (CD)', 'itemMeasurement': 16, 'itemCategory': 'Electronics'},
            {'itemName': 'Bag of Chips', 'itemMeasurement': 150, 'itemCategory': 'Food'},
            {'itemName': 'Pair of Shoes', 'itemMeasurement': 1000, 'itemCategory': 'Clothing'},
            {'itemName': 'Lightbulb', 'itemMeasurement': 50, 'itemCategory': 'Electronics'},
            {'itemName': 'Standard Refrigerator', 'itemMeasurement': 150000, 'itemCategory': 'Household Items'},
            {'itemName': 'Baseball Cap', 'itemMeasurement': 100, 'itemCategory': 'Accessories'},
            {'itemName': 'Soccer Cleats', 'itemMeasurement': 300, 'itemCategory': 'Footwear'},
            {'itemName': 'Tennis Racket', 'itemMeasurement': 300, 'itemCategory': 'Sports Equipment'},
            {'itemName': 'Adult Rabbit', 'itemMeasurement': 2000, 'itemCategory': 'Pets'},
            {'itemName': 'Bag of Sugar', 'itemMeasurement': 2000, 'itemCategory': 'Food'},
            {'itemName': 'Chocolate Bar', 'itemMeasurement': 100, 'itemCategory': 'Food'},
            {'itemName': 'Adult Polar Bear', 'itemMeasurement': 450000, 'itemCategory': 'Wildlife'},
            {'itemName': 'Water Bottle', 'itemMeasurement': 500, 'itemCategory': 'Household Items'},
            {'itemName': 'Average Car', 'itemMeasurement': 1500, 'itemCategory': 'Automobile'},
            {'itemName': 'Fire Extinguisher', 'itemMeasurement': 5000, 'itemCategory': 'Safety Equipment'},
            {'itemName': 'Small Plant', 'itemMeasurement': 500, 'itemCategory': 'Nature'},
            {'itemName': 'Kitchen Blender', 'itemMeasurement': 5000, 'itemCategory': 'Household Items'},
            {'itemName': 'Adult Kangaroo', 'itemMeasurement': 55000, 'itemCategory': 'Wildlife'},
            {'itemName': 'Small Notebook', 'itemMeasurement': 200, 'itemCategory': 'Stationery'},
            {'itemName': 'Tablet', 'itemMeasurement': 500, 'itemCategory': 'Electronics'},
            {'itemName': 'Small Lemon', 'itemMeasurement': 100, 'itemCategory': 'Food'},
            {'itemName': 'Adult Gorilla', 'itemMeasurement': 160000, 'itemCategory': 'Wildlife'},
            {'itemName': 'Adult Ostrich', 'itemMeasurement': 145000, 'itemCategory': 'Wildlife'},
            {'itemName': 'Adult Chimpanzee', 'itemMeasurement': 40000, 'itemCategory': 'Wildlife'},
            {'itemName': 'Chicken Egg (average)', 'itemMeasurement': 50, 'itemCategory': 'Food'},
            {'itemName': 'Compact Mirror', 'itemMeasurement': 100, 'itemCategory': 'Accessories'},
            {'itemName': 'Bag of Coffee Beans', 'itemMeasurement': 500, 'itemCategory': 'Food'},
            {'itemName': 'Straw Hat', 'itemMeasurement': 150, 'itemCategory': 'Clothing'},
            {'itemName': 'Small Pinecone', 'itemMeasurement': 5, 'itemCategory': 'Nature'},
            {'itemName': 'Bottle of Water', 'itemMeasurement': 500, 'itemCategory': 'Food'},
            {'itemName': 'Adult Sperm Whale', 'itemMeasurement': 45000000, 'itemCategory': 'Wildlife'},
            {'itemName': 'Human Lungs', 'itemMeasurement': 1300, 'itemCategory': 'Human'},

        ]

        for item in item_weights:
            item = Item(
                itemName=item['itemName'],
                itemMeasurement=item['itemMeasurement'],
                itemCategory=ItemCategory.objects.get(itemCategory=item['itemCategory']),
                measurementType=MeasurementType.objects.get(measurementType="weight")
            )
            item.save()
            # self.stdout.write(f'Successfully added {item["itemName"]} to Item class.')

        items_lengths = [
            {'itemName': 'Grain of Salt', 'itemMeasurement': 0.05, 'itemCategory': 'Food'},
            {'itemName': 'Feather', 'itemMeasurement': 0.1, 'itemCategory': 'Nature'},
            {'itemName': 'Ant', 'itemMeasurement': 0.1, 'itemCategory': 'Insect'},
            {'itemName': 'Paperclip', 'itemMeasurement': 1, 'itemCategory': 'Stationery'},
            {'itemName': 'Pencil', 'itemMeasurement': 15, 'itemCategory': 'Stationery'},
            {'itemName': 'Apple', 'itemMeasurement': 8, 'itemCategory': 'Fruit'},
            {'itemName': 'Smartphone', 'itemMeasurement': 15, 'itemCategory': 'Electronics'},
            {'itemName': 'Can of Soda', 'itemMeasurement': 13, 'itemCategory': 'Food'},
            {'itemName': 'Laptop', 'itemMeasurement': 35, 'itemCategory': 'Electronics'},
            {'itemName': 'Small Dog', 'itemMeasurement': 40, 'itemCategory': 'Household Items'},
            {'itemName': 'Watermelon', 'itemMeasurement': 25, 'itemCategory': 'Fruit'},
            {'itemName': 'Car Tire', 'itemMeasurement': 63, 'itemCategory': 'Automobile'},
            {'itemName': 'Elephant', 'itemMeasurement': 8000, 'itemCategory': 'Wildlife'},
            {'itemName': 'Small Aircraft', 'itemMeasurement': 12, 'itemCategory': 'Transportation'},
            {'itemName': 'Adult Human', 'itemMeasurement': 170, 'itemCategory': 'Human'},
            {'itemName': 'Blue Whale', 'itemMeasurement': 3000, 'itemCategory': 'Marine Life'},
            {'itemName': 'Small Car', 'itemMeasurement': 4, 'itemCategory': 'Automobile'},
            {'itemName': 'Motorcycle', 'itemMeasurement': 2, 'itemCategory': 'Transportation'},
            {'itemName': 'Baseball', 'itemMeasurement': 23, 'itemCategory': 'Sports Equipment'},
            {'itemName': 'Basketball', 'itemMeasurement': 24, 'itemCategory': 'Sports Equipment'},
            {'itemName': 'Adult Lion', 'itemMeasurement': 243, 'itemCategory': 'Wildlife'},
            {'itemName': 'Small Elephant', 'itemMeasurement': 96, 'itemCategory': 'Wildlife'},
            {'itemName': 'Laptop Bag', 'itemMeasurement': 50, 'itemCategory': 'Electronics'},
            {'itemName': 'Large Truck', 'itemMeasurement': 26, 'itemCategory': 'Automobile'},
            {'itemName': 'Adult Giraffe', 'itemMeasurement': 520, 'itemCategory': 'Wildlife'},
            {'itemName': 'Bag of Flour', 'itemMeasurement': 8, 'itemCategory': 'Food'},
            {'itemName': 'Human Brain', 'itemMeasurement': 15, 'itemCategory': 'Human'},
            {'itemName': 'Backpack', 'itemMeasurement': 50, 'itemCategory': 'Household Items'},
            {'itemName': 'Desktop Computer', 'itemMeasurement': 45, 'itemCategory': 'Electronics'},
            {'itemName': 'Small TV', 'itemMeasurement': 25, 'itemCategory': 'Electronics'},
            {'itemName': 'Soccer Ball', 'itemMeasurement': 22, 'itemCategory': 'Sports Equipment'},
            {'itemName': 'Adult Tiger', 'itemMeasurement': 250, 'itemCategory': 'Wildlife'},
            {'itemName': 'Adult Rhino', 'itemMeasurement': 1500, 'itemCategory': 'Wildlife'},
            {'itemName': 'Small Boat', 'itemMeasurement': 50, 'itemCategory': 'Transportation'},
            {'itemName': 'Coffee Cup (empty)', 'itemMeasurement': 12, 'itemCategory': 'Household Items'},
            {'itemName': 'Canoe', 'itemMeasurement': 460, 'itemCategory': 'Transportation'},
            {'itemName': 'Car Battery', 'itemMeasurement': 50, 'itemCategory': 'Automobile'},
            {'itemName': 'Adult Hippo', 'itemMeasurement': 470, 'itemCategory': 'Wildlife'},
            {'itemName': 'Small Avocado', 'itemMeasurement': 12, 'itemCategory': 'Food'},
            {'itemName': 'Motorcycle Helmet', 'itemMeasurement': 23, 'itemCategory': 'Accessories'},
            {'itemName': 'Pair of Jeans', 'itemMeasurement': 100, 'itemCategory': 'Clothing'},
            {'itemName': 'Large Pumpkin', 'itemMeasurement': 50, 'itemCategory': 'Food'},
            {'itemName': 'Desktop Monitor', 'itemMeasurement': 40, 'itemCategory': 'Electronics'},
            {'itemName': 'Small Cat', 'itemMeasurement': 40, 'itemCategory': 'Household Items'},
            {'itemName': 'Adult Kangaroo', 'itemMeasurement': 100, 'itemCategory': 'Wildlife'},
            {'itemName': 'Small Fish (e.g., Goldfish)', 'itemMeasurement': 10, 'itemCategory': 'Pets'},
            {'itemName': 'Smartphone Charger', 'itemMeasurement': 6, 'itemCategory': 'Electronics'},
            {'itemName': 'Small Backpack', 'itemMeasurement': 30, 'itemCategory': 'Household Items'},
            {'itemName': 'Compact Disc (CD)', 'itemMeasurement': 12, 'itemCategory': 'Electronics'},
            {'itemName': 'Bag of Chips', 'itemMeasurement': 20, 'itemCategory': 'Food'},
            {'itemName': 'Pair of Shoes', 'itemMeasurement': 30, 'itemCategory': 'Clothing'},
            {'itemName': 'Lightbulb', 'itemMeasurement': 12, 'itemCategory': 'Electronics'},
            {'itemName': 'Standard Refrigerator', 'itemMeasurement': 180, 'itemCategory': 'Household Items'},
            {'itemName': 'Baseball Cap', 'itemMeasurement': 20, 'itemCategory': 'Accessories'},
            {'itemName': 'Soccer Cleats', 'itemMeasurement': 28, 'itemCategory': 'Footwear'},
            {'itemName': 'Tennis Racket', 'itemMeasurement': 70, 'itemCategory': 'Sports Equipment'},
            {'itemName': 'Adult Rabbit', 'itemMeasurement': 40, 'itemCategory': 'Pets'},
            {'itemName': 'Bag of Sugar', 'itemMeasurement': 25, 'itemCategory': 'Food'},
            {'itemName': 'Chocolate Bar', 'itemMeasurement': 18, 'itemCategory': 'Food'},
            {'itemName': 'Adult Polar Bear', 'itemMeasurement': 300, 'itemCategory': 'Wildlife'},
            {'itemName': 'Water Bottle', 'itemMeasurement': 18, 'itemCategory': 'Household Items'},
            {'itemName': 'Average Car', 'itemMeasurement': 4, 'itemCategory': 'Automobile'},
            {'itemName': 'Fire Extinguisher', 'itemMeasurement': 40, 'itemCategory': 'Safety Equipment'},
            {'itemName': 'Small Plant', 'itemMeasurement': 20, 'itemCategory': 'Nature'},
            {'itemName': 'Kitchen Blender', 'itemMeasurement': 40, 'itemCategory': 'Household Items'},
            {'itemName': 'Adult Kangaroo', 'itemMeasurement': 100, 'itemCategory': 'Wildlife'},
            {'itemName': 'Small Notebook', 'itemMeasurement': 15, 'itemCategory': 'Stationery'},
            {'itemName': 'Tablet', 'itemMeasurement': 20, 'itemCategory': 'Electronics'},
            {'itemName': 'Small Lemon', 'itemMeasurement': 10, 'itemCategory': 'Food'},
            {'itemName': 'Adult Gorilla', 'itemMeasurement': 170, 'itemCategory': 'Wildlife'},
            {'itemName': 'Adult Ostrich', 'itemMeasurement': 210, 'itemCategory': 'Wildlife'},
            {'itemName': 'Adult Chimpanzee', 'itemMeasurement': 70, 'itemCategory': 'Wildlife'},
            {'itemName': 'Chicken Egg', 'itemMeasurement': 5, 'itemCategory': 'Food'},
            {'itemName': 'Compact Mirror', 'itemMeasurement': 10, 'itemCategory': 'Accessories'},
            {'itemName': 'Bag of Coffee Beans', 'itemMeasurement': 15, 'itemCategory': 'Food'},
            {'itemName': 'Straw Hat', 'itemMeasurement': 30, 'itemCategory': 'Clothing'},
            {'itemName': 'Small Pinecone', 'itemMeasurement': 5, 'itemCategory': 'Nature'},
            {'itemName': 'Bottle of Water', 'itemMeasurement': 20, 'itemCategory': 'Food'},
            {'itemName': 'Adult Sperm Whale', 'itemMeasurement': 1800, 'itemCategory': 'Wildlife'},
            {'itemName': 'Human Lungs', 'itemMeasurement': 20, 'itemCategory': 'Human'},
        ]

        for item in items_lengths:
            item = Item(
                itemName=item['itemName'],
                itemMeasurement=item['itemMeasurement'],
                itemCategory=ItemCategory.objects.get(itemCategory=item['itemCategory']),
                measurementType=MeasurementType.objects.get(measurementType="length")
            )
            item.save()
            # self.stdout.write(f'Successfully added {item["itemName"]} to Item class.')

        self.stdout.write(self.style.SUCCESS('Successfully added all animals to Item class.'))


